[features]
seeds = false
skip-lint = false
[programs.localnet]
lunarpool = "BScWpTj5Jyp9EJJoLaKMGLEoRAxVPXqr24kvU28NPVeH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/macbookpro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
